variables:
#修改项目名和端口
  PROJECT_NAME: label_tool
  OUT_PORT: 11000

label_tool:
  allow_failure: true
  script:
    - pwd
    - docker build -t  $PROJECT_NAME .
    - docker stack deploy -c docker-compose.yml label_tool

  tags:
    - global