version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: label_tool
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "11000:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
networks:
  webnet: