version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: label_tool
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "11000:80"
    networks:
      - webnet
networks:
  webnet: